version: '3.8'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 16686:16686
      - 5778:5778
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
    hostname: jaeger
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./etc/prometheus.yaml:/etc/prometheus.yaml
    entrypoint:
      - /bin/prometheus
      - --config.file=/etc/prometheus.yaml
    ports:
      - "9090:9090"
    hostname: prometheus

  nestjs-supplier:
    build:
      context: ./supplier
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
      - 9464:9464
    depends_on:
      - jaeger
      - kafka
    restart: on-failure
  nestjs-customer:
    build:
      context: ./customer
      dockerfile: ./Dockerfile
    ports:
      - 4000:4000
      - 9465:9465
    depends_on:
      - jaeger
      - kafka
      - nestjs-supplier
      - nestjs-customer2
    restart: on-failure
  nestjs-customer2:
    build:
      context: ./customer2
      dockerfile: ./Dockerfile
    ports:
      - 9000:9000
      - 9466:9466
    depends_on:
      - jaeger
      - kafka
    restart: on-failure

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
