global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'nestjs-warehouse-api'
    metrics_path: /metrics
    static_configs:
    - targets: ['nestjs-warehouse:9464']

  - job_name: 'nestjs-accounting-api'
    metrics_path: /metrics
    static_configs:
    - targets: ['nestjs-accounting:9465']

  - job_name: 'nestjs-delivery-api'
    metrics_path: /metrics
    static_configs:
    - targets: ['nestjs-delivery:9466']

  - job_name: 'volume_exporter'
    metrics_path: /metrics
    static_configs:
    - targets: ['volume_exporter:9888']
