global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'nestjs-supplier-api'
    metrics_path: /metrics
    static_configs:
    - targets: ['nestjs-supplier:9464']

  - job_name: 'nestjs-customer-api'
    metrics_path: /metrics
    static_configs:
    - targets: ['nestjs-customer:9465']

  - job_name: 'nestjs-customer-api'
    metrics_path: /metrics
    static_configs:
    - targets: ['nestjs-customer2:9466']

  - job_name: 'volume_exporter'
    metrics_path: /metrics
    static_configs:
    - targets: ['volume_exporter:9888']
